import { Locale } from "./types";
const hy={
home:"Գլխավոր",market:"Զարդեր",rates:"Ոսկու գներ",profile:"Պրոֆիլ",seller:"Վաճառողի պորտալ",finance:"Ֆինանսներ",admin:"Կառավարում",vip:"Ընտանեկան",signin:"Մուտք",signout:"Դուրս գալ",register:"Գրանցվել",language:"Լեզու",
heroEyebrow:"Նոր սերնդի ոսկու հարթակ",heroTitle:"Ոսկու շուկան՝ նոր մակարդակում",heroText:"Բացահայտեք ընտրված զարդեր, վստահելի վաճառողներ և իրական ժամանակում թարմացվող ոսկու գներ՝ մեկ պրեմիում հարթակում։",explore:"Բացահայտել զարդերը",seeRates:"Դիտել գները",trusted:"Ստուգված վաճառողներ",live:"Ուղիղ գներ",private:"Մասնավոր հավաքածու",premium:"Պրեմիում ընտրանի",
featured:"Ընտրված զարդեր",featuredText:"Ձեռքով ընտրված առաջարկներ GoldMate գործընկերներից։",viewAll:"Դիտել բոլորը",why:"Ինչու GoldMate",why1:"Մեկ հարթակ՝ բազմաթիվ վաճառողների համար",why2:"Հստակ տվյալներ՝ հարգ, քաշ, գույն և քարեր",why3:"Վաճառողի հաստատում՝ մինչև հրապարակումը",why4:"ՀՀ ԿԲ XAU պաշտոնական ցուցանիշի հիման վրա հաշվարկվող գներ",
search:"Որոնել",all:"Բոլորը",purity:"Հարգ",color:"Գույն",category:"Տեսակ",price:"Գին",weight:"Քաշ",yellow:"Դեղին ոսկի",white:"Սպիտակ ոսկի",rose:"Վարդագույն ոսկի",mixed:"Խառը",ring:"Մատանի",earrings:"Ականջօղ",necklace:"Վզնոց",bracelet:"Ապարանջան",chain:"Շղթա",pendant:"Կախազարդ",wedding:"Ամուսնական",other:"Այլ",new:"Նոր",preowned:"Նախկինում օգտագործված",
rateTitle:"Ոսկու գները",rateText:"585, 750, 916 և 999 հարգերի գները ավտոմատ հաշվարկվում են ՀՀ Կենտրոնական բանկի պաշտոնական XAU ցուցանիշից։",spot:"Միջազգային spot",usdAmd:"USD / AMD",perGram:"1 գրամի արժեք",updated:"Թարմացվել է",calculator:"Հաշվիչ",estimate:"Մոտավոր արժեք",buyPrice:"Առքի գին",sellPrice:"Վաճառքի գին",marketReference:"Շուկայական հղումային արժեք",disclaimer:"Տվյալները տեղեկատվական են։ Վերջնական առքուվաճառքի գինը կարող է տարբերվել ըստ ապրանքի, աշխատանքի և վաճառողի պայմանների։",
profileTitle:"Իմ պրոֆիլը",account:"Հաշիվ",myOrders:"Իմ պատվերները",editProfile:"Խմբագրել պրոֆիլը",name:"Անուն",email:"Էլ. փոստ",phone:"Հեռախոս",save:"Պահպանել",google:"Շարունակել Google-ով",password:"Գաղտնաբառ",noAccount:"Չունե՞ք հաշիվ",haveAccount:"Արդեն ունե՞ք հաշիվ",createAccount:"Ստեղծել հաշիվ",sellerApply:"Դառնալ վաճառող",sellerPending:"Հայտը սպասում է հաստատման",sellerApproved:"Վաճառողի հաշիվը հաստատված է",
applyTitle:"Վաճառողի հայտ",applyText:"GoldMate-ում հրապարակելու համար յուրաքանչյուր վաճառող նախ անցնում է ադմինի հաստատում։",brandName:"Բրենդի / խանութի անուն",marketLocation:"Տեղադրություն / շուկա",about:"Ձեր գործունեության մասին",send:"Ուղարկել հայտը",
sellerTitle:"Վաճառողի պորտալ",products:"Ապրանքներ",orders:"Պատվերներ",brandProfile:"Բրենդի պրոֆիլ",addProduct:"Ավելացնել զարդ",editBrand:"Խմբագրել բրենդը",brandLogo:"Լոգո",brandCover:"Շապիկ",instagram:"Instagram",whatsapp:"WhatsApp",address:"Հասցե",bio:"Նկարագրություն",verified:"Հաստատված",status:"Կարգավիճակ",stock:"Քանակ",sku:"Կոդ",size:"Չափ",gemstone:"Քար",stoneCt:"Քարի քաշ (ct)",description:"Նկարագրություն",photos:"Նկարներ",publish:"Հրապարակել",draft:"Սևագիր",active:"Ակտիվ",sold:"Վաճառված",archived:"Արխիվացված",
orderNow:"Պատվիրել",orderTitle:"Պատվերի հարցում",fullName:"Անուն ազգանուն",deliveryAddress:"Առաքման հասցե",comment:"Մեկնաբանություն",submitOrder:"Ուղարկել պատվերը",orderSent:"Պատվերն ուղարկված է",sellerContact:"Վաճառող",brandStore:"Բրենդի էջ",
financeTitle:"Ֆինանսներ",income:"Եկամուտ",expense:"Ծախս",profit:"Շահույթ",addEntry:"Ավելացնել գրառում",amount:"Գումար",date:"Ամսաթիվ",note:"Նշում",financeCategory:"Կատեգորիա",
adminTitle:"GoldMate կառավարում",sellerApps:"Վաճառողների հայտեր",users:"Օգտատերեր",pricing:"Գնային կարգավորումներ",approve:"Հաստատել",reject:"Մերժել",buyAdjustment:"Առքի շեղում spot-ից (%)",sellAdjustment:"Վաճառքի հավելում spot-ին (%)",savePricing:"Պահպանել կարգավորումները",
vipTitle:"Մասնավոր ընտանեկան պահոց",vipText:"Ադմինի անձնական փակ հավաքածու։ Մուտքը տրվում է միայն ընտրված ընտանիքի անդամներին։",purchaseValue:"Գնման ընդհանուր արժեք",currentValue:"Ընթացիկ մոտավոր արժեք",wealth:"Ընդհանուր գնահատված կարողություն",totalWeight:"Ընդհանուր քաշ",items:"Զարդերի քանակ",addVault:"Ավելացնել ձեռքբերում",purchaseDate:"Գնման ամսաթիվ",purchasePrice:"Գնման գին",acquiredFrom:"Որտեղից է ձեռք բերվել",share:"Կիսվել ընտանիքի անդամի հետ",sharedWith:"Մուտք ունեցողներ",addEmail:"Ավելացնել էլ. փոստ",remove:"Հեռացնել",noAccess:"Այս բաժինը հասանելի չէ ձեր հաշվին",readOnly:"Դիտման ռեժիմ",
langHy:"Հայերեն",langEn:"Անգլերեն",langRu:"Ռուսերեն",roleBuyer:"Գնորդ",roleSeller:"Վաճառող",roleAdmin:"Ադմին",orderNew:"Նոր պատվեր",orderConfirmed:"Հաստատված",orderCompleted:"Ավարտված",orderCancelled:"Չեղարկված",brandNotReady:"Բրենդի էջը դեռ պատրաստ չէ",empty:"Տվյալներ դեռ չկան",loading:"Բեռնվում է…",error:"Տեղի ունեցավ սխալ",success:"Պահպանված է",back:"Հետ",close:"Փակել"
};
const en={
home:"Home",market:"Jewelry",rates:"Gold Rates",profile:"Profile",seller:"Seller Portal",finance:"Finance",admin:"Admin",vip:"Family Vault",signin:"Sign in",signout:"Sign out",register:"Register",language:"Language",
heroEyebrow:"A new generation gold platform",heroTitle:"The gold market, elevated",heroText:"Discover curated jewelry, trusted sellers and automatically updated gold rates in one premium platform.",explore:"Explore jewelry",seeRates:"View gold rates",trusted:"Approved sellers",live:"Live pricing",private:"Private collection",premium:"Premium selection",
featured:"Featured jewelry",featuredText:"Hand-picked pieces from GoldMate partners.",viewAll:"View all",why:"Why GoldMate",why1:"One platform for multiple sellers",why2:"Clear specs: purity, weight, color and stones",why3:"Seller approval before publishing",why4:"Rates calculated from the official CBA XAU reference",
search:"Search",all:"All",purity:"Purity",color:"Color",category:"Category",price:"Price",weight:"Weight",yellow:"Yellow gold",white:"White gold",rose:"Rose gold",mixed:"Mixed",ring:"Ring",earrings:"Earrings",necklace:"Necklace",bracelet:"Bracelet",chain:"Chain",pendant:"Pendant",wedding:"Wedding",other:"Other",new:"New",preowned:"Pre-owned",
rateTitle:"Gold rates",rateText:"585, 750, 916 and 999 purity rates are calculated automatically from the official Central Bank of Armenia XAU reference.",spot:"International spot",usdAmd:"USD / AMD",perGram:"Per gram",updated:"Updated",calculator:"Calculator",estimate:"Estimated value",buyPrice:"Buy price",sellPrice:"Sell price",marketReference:"Market reference",disclaimer:"Rates are informational. Final transaction prices may vary by item, workmanship and seller terms.",
profileTitle:"My profile",account:"Account",myOrders:"My orders",editProfile:"Edit profile",name:"Name",email:"Email",phone:"Phone",save:"Save",google:"Continue with Google",password:"Password",noAccount:"Need an account?",haveAccount:"Already have an account?",createAccount:"Create account",sellerApply:"Become a seller",sellerPending:"Application awaiting approval",sellerApproved:"Seller account approved",
applyTitle:"Seller application",applyText:"Every seller must be approved by GoldMate administration before publishing.",brandName:"Brand / store name",marketLocation:"Location / market",about:"About your business",send:"Send application",
sellerTitle:"Seller portal",products:"Products",orders:"Orders",brandProfile:"Brand profile",addProduct:"Add jewelry",editBrand:"Edit brand",brandLogo:"Logo",brandCover:"Cover",instagram:"Instagram",whatsapp:"WhatsApp",address:"Address",bio:"Description",verified:"Verified",status:"Status",stock:"Stock",sku:"SKU",size:"Size",gemstone:"Gemstone",stoneCt:"Stone weight (ct)",description:"Description",photos:"Photos",publish:"Publish",draft:"Draft",active:"Active",sold:"Sold",archived:"Archived",
orderNow:"Order",orderTitle:"Order request",fullName:"Full name",deliveryAddress:"Delivery address",comment:"Comment",submitOrder:"Submit order",orderSent:"Order submitted",sellerContact:"Seller",brandStore:"Brand page",
financeTitle:"Finance",income:"Income",expense:"Expense",profit:"Profit",addEntry:"Add entry",amount:"Amount",date:"Date",note:"Note",financeCategory:"Category",
adminTitle:"GoldMate administration",sellerApps:"Seller applications",users:"Users",pricing:"Pricing settings",approve:"Approve",reject:"Reject",buyAdjustment:"Buy adjustment from spot (%)",sellAdjustment:"Sell premium over spot (%)",savePricing:"Save settings",
vipTitle:"Private family vault",vipText:"The administrator's private collection. Access is granted only to selected family members.",purchaseValue:"Total purchase value",currentValue:"Estimated current value",wealth:"Estimated total wealth",totalWeight:"Total weight",items:"Number of pieces",addVault:"Add acquisition",purchaseDate:"Purchase date",purchasePrice:"Purchase price",acquiredFrom:"Acquired from",share:"Share with family member",sharedWith:"People with access",addEmail:"Add email",remove:"Remove",noAccess:"This section is not available to your account",readOnly:"View-only mode",
langHy:"Armenian",langEn:"English",langRu:"Russian",roleBuyer:"Buyer",roleSeller:"Seller",roleAdmin:"Admin",orderNew:"New order",orderConfirmed:"Confirmed",orderCompleted:"Completed",orderCancelled:"Cancelled",brandNotReady:"Brand page is not ready yet",empty:"No data yet",loading:"Loading…",error:"Something went wrong",success:"Saved",back:"Back",close:"Close"
};
const ru={
home:"Главная",market:"Украшения",rates:"Цены на золото",profile:"Профиль",seller:"Портал продавца",finance:"Финансы",admin:"Управление",vip:"Семейное хранилище",signin:"Войти",signout:"Выйти",register:"Регистрация",language:"Язык",
heroEyebrow:"Золотая платформа нового поколения",heroTitle:"Рынок золота на новом уровне",heroText:"Открывайте отобранные украшения, проверенных продавцов и автоматически обновляемые цены на золото на одной премиальной платформе.",explore:"Смотреть украшения",seeRates:"Смотреть цены",trusted:"Проверенные продавцы",live:"Актуальные цены",private:"Частная коллекция",premium:"Премиальная подборка",
featured:"Избранные украшения",featuredText:"Отобранные предложения партнеров GoldMate.",viewAll:"Смотреть все",why:"Почему GoldMate",why1:"Одна платформа для множества продавцов",why2:"Понятные характеристики: проба, вес, цвет и камни",why3:"Проверка продавца до публикации",why4:"Расчёт цен по официальному референсу XAU ЦБ Армении",
search:"Поиск",all:"Все",purity:"Проба",color:"Цвет",category:"Категория",price:"Цена",weight:"Вес",yellow:"Желтое золото",white:"Белое золото",rose:"Розовое золото",mixed:"Комбинированное",ring:"Кольцо",earrings:"Серьги",necklace:"Колье",bracelet:"Браслет",chain:"Цепочка",pendant:"Подвеска",wedding:"Обручальные",other:"Другое",new:"Новое",preowned:"Б/у",
rateTitle:"Цены на золото",rateText:"Цены проб 585, 750, 916 и 999 автоматически рассчитываются по официальному референсу XAU Центрального банка Армении.",spot:"Мировой spot",usdAmd:"USD / AMD",perGram:"За грамм",updated:"Обновлено",calculator:"Калькулятор",estimate:"Примерная стоимость",buyPrice:"Цена покупки",sellPrice:"Цена продажи",marketReference:"Рыночный ориентир",disclaimer:"Данные носят информационный характер. Итоговая цена может отличаться в зависимости от изделия, работы и условий продавца.",
profileTitle:"Мой профиль",account:"Аккаунт",myOrders:"Мои заказы",editProfile:"Редактировать профиль",name:"Имя",email:"Эл. почта",phone:"Телефон",save:"Сохранить",google:"Продолжить с Google",password:"Пароль",noAccount:"Нет аккаунта?",haveAccount:"Уже есть аккаунт?",createAccount:"Создать аккаунт",sellerApply:"Стать продавцом",sellerPending:"Заявка ожидает подтверждения",sellerApproved:"Аккаунт продавца подтвержден",
applyTitle:"Заявка продавца",applyText:"Для публикации на GoldMate каждый продавец проходит одобрение администратора.",brandName:"Название бренда / магазина",marketLocation:"Местоположение / рынок",about:"О вашем бизнесе",send:"Отправить заявку",
sellerTitle:"Портал продавца",products:"Товары",orders:"Заказы",brandProfile:"Профиль бренда",addProduct:"Добавить украшение",editBrand:"Редактировать бренд",brandLogo:"Логотип",brandCover:"Обложка",instagram:"Instagram",whatsapp:"WhatsApp",address:"Адрес",bio:"Описание",verified:"Проверен",status:"Статус",stock:"Количество",sku:"Артикул",size:"Размер",gemstone:"Камень",stoneCt:"Вес камня (ct)",description:"Описание",photos:"Фотографии",publish:"Опубликовать",draft:"Черновик",active:"Активно",sold:"Продано",archived:"Архив",
orderNow:"Заказать",orderTitle:"Заявка на заказ",fullName:"Имя и фамилия",deliveryAddress:"Адрес доставки",comment:"Комментарий",submitOrder:"Отправить заказ",orderSent:"Заказ отправлен",sellerContact:"Продавец",brandStore:"Страница бренда",
financeTitle:"Финансы",income:"Доход",expense:"Расход",profit:"Прибыль",addEntry:"Добавить запись",amount:"Сумма",date:"Дата",note:"Заметка",financeCategory:"Категория",
adminTitle:"Управление GoldMate",sellerApps:"Заявки продавцов",users:"Пользователи",pricing:"Настройки цен",approve:"Одобрить",reject:"Отклонить",buyAdjustment:"Отклонение покупки от spot (%)",sellAdjustment:"Наценка продажи к spot (%)",savePricing:"Сохранить настройки",
vipTitle:"Частное семейное хранилище",vipText:"Личная закрытая коллекция администратора. Доступ предоставляется только выбранным членам семьи.",purchaseValue:"Общая стоимость покупки",currentValue:"Оценочная текущая стоимость",wealth:"Оценочная стоимость капитала",totalWeight:"Общий вес",items:"Количество изделий",addVault:"Добавить покупку",purchaseDate:"Дата покупки",purchasePrice:"Цена покупки",acquiredFrom:"Где приобретено",share:"Поделиться с членом семьи",sharedWith:"Имеют доступ",addEmail:"Добавить email",remove:"Удалить",noAccess:"Этот раздел недоступен вашему аккаунту",readOnly:"Режим просмотра",
langHy:"Армянский",langEn:"Английский",langRu:"Русский",roleBuyer:"Покупатель",roleSeller:"Продавец",roleAdmin:"Администратор",orderNew:"Новый заказ",orderConfirmed:"Подтвержден",orderCompleted:"Завершен",orderCancelled:"Отменен",brandNotReady:"Страница бренда пока не готова",empty:"Данных пока нет",loading:"Загрузка…",error:"Произошла ошибка",success:"Сохранено",back:"Назад",close:"Закрыть"
};
export const dictionaries={hy,en,ru}; export type Dict=typeof hy; export const getDict=(l:Locale)=>dictionaries[l];
